import axios from "axios";
import { getGlobalPrefix } from "../../service.js";
import { getContent } from "../../../utils/format-util.js";
import { sendMessageComplete, sendMessageFailed, sendMessageQuery, sendMessageStateQuote } from "../../chat-zalo/chat-style/chat-style.js";
import { API_KEY_HUNGDEV } from "../api-hungdev/aio-downlink.js";

const URL_GPT = "https://api.hungdev.id.vn/ai/chatbot";

export async function callGPTAPI(question) {
  try {
    const response = await axios.post(`${URL_GPT}?apikey=${API_KEY_HUNGDEV}`, {
      content: question,
      model: "gpt-4o",
    }, {
      headers: {
        'Content-Type': 'application/json'
      }
    });

    const data = response.data;
    return data.data.response.replace("Generated by BLACKBOX.AI, try unlimited chat https://www.blackbox.ai\n\n", "");
  } catch (error) {
    console.error("Lỗi khi gọi API GPT:", error);
    return null;
  }
}

export async function askGPTCommand(api, message, aliasCommand) {
  const content = getContent(message);
  const threadId = message.threadId;
  const prefix = getGlobalPrefix();

  const question = content.replace(`${prefix}${aliasCommand}`, "").trim();
  if (question === "") {
    await sendMessageQuery(api, message, "Vui lòng nhập câu hỏi cần giải đáp!");
    return;
  }

  try {
    const replyText = await callGPTAPI(question);

    if (!replyText) {
      throw new Error("Không nhận được phản hồi từ API");
    }

    await sendMessageStateQuote(api, message, replyText, true, 1800000, false);

  } catch (error) {
    console.error("Lỗi khi xử lý yêu cầu GPT:", error);
    await sendMessageFailed(api, message, "Xin lỗi, có lỗi xảy ra khi xử lý yêu cầu của bạn.");
  }
}

